pr1
eparoshin/project_kompute pull request #1
Opened 2024-01-21 17:03 UTC by eparoshin

Первый пулл-реквест:

сделал библиотеку, которую потом слинкую с TypingAnalisys, так удобнее тестировать, пока там бинарник, который просто инициализирует класс из библиотеки, но потом я его уберу.

пока не готовы тесты, и генерация spirv из шейдеров на glsl, из spirv будут сгенерированы header файлы, где бинарник хранится в массиве uint_32, они будут подключены к compute_functions.h также сами шейдеры неправильно работают(изначально неправильно понял алгоритм, пока не переписал). также пока что инициализируется нулевой vulkan device, с одной очередью, вместо этого нужно будет получать список доступных устройств, инициализировать самое производительное, и все доступные очереди в нем.

2024-03-04 12:52 UTC, DimaTrushin requested changes
Обрати внимание, что я не повторял замечания. Если одна и та же ошибка всречалась несколько раз, я комментировал лишь единожды. Потому я ожидаю, что ты поправишь все аналогичные замечания всюду.

Обрати внимание на архитектуру. Я подробно рассказал, как у меня организован Cuda код. Постарайся сделать по аналогии.

Несмотря на то, что Kompute использует shared_ptr в своем api, это не значит, что мы должны его использовать на своей стороне. Я уверен, что можно везде избавиться от shared_ptr в нашем коде.

И еще почему у тебя есть кодогенерация питоном? Что мешало эти хедеры написать самому руками? Это часть Kompute парадигмы?

Я еще добавил местами пометки по стилю кода, который принят у меня в проекте. Обрати на них тоже внимание.

И еще надо бы обсудить детали того, что тут в коде происходит.

2024-03-04 12:52 UTC, DimaTrushin commented on .clang-format
Потом надо будет взять clang-format из моего репозитория.

2024-03-04 12:52 UTC, DimaTrushin commented on README.md
> +
Хорошо бы добавить инструкцию по удовлетворению requirements, ну или хотя бы ссылки на то как и куда они устанавливаются.

2024-03-04 12:52 UTC, DimaTrushin commented on README.md
> +kompute(as submodule)
И еще если проект с git submodules, то его надо специальным образом клонировать. Это все надо добавить в инструкцию.

2024-03-04 12:52 UTC, DimaTrushin commented on README.md
> +
Сделай нормальный перечень через -

2024-03-04 12:52 UTC, DimaTrushin commented on README.md
> +requirements:
Выдели заголовочным шрифтом через # в нужном количестве.

2024-03-04 12:52 UTC, DimaTrushin commented on subprojects/.clang-format
А зачем этот файл, если ты все subprojects игнорируешь через clang-format-ignore?

2024-03-04 12:52 UTC, DimaTrushin commented on test/test_fill_plots.cpp
> +using TVectorD = NKomputeDevice::TVectorD;
Я использую заголовочную букву T только в начале  названий шаблонных аргументов. Для типов я использую заголовочную букву C, а для namespace-ов заголовочные буквы NS.

2024-03-04 12:52 UTC, DimaTrushin commented on test/test_fill_plots.cpp
> +    device.FillPlots(samples, x, &D0Y0, &D1Y0, &D0Y1, &D1Y1, &D0Y2, &D1Y2);
Замерь по времени сколько этот метод работает если:
1) samples.size() == 2500
2) x.size() == 2500

2024-03-04 12:52 UTC, DimaTrushin commented on lib/shaders/meson.build
Судя по всему ты делаешь кодогенерацию из comp файлов в hpp и spv файлы. Есть несколько вопросов:
1) Я так понимаю ничего не мешает сделать h файлы, это лишь условность (просто для единообразия в проекте).
2) Можно ли обойтись без кодогенерации. Как минимум генерация h файлов говорит, что можно было бы сразу их создать. Зачем их генерировать? В чем сокральный смысл?

Мне генерация всегда не нравится тем, что у тебя нет единого источника правды. Так будет две разные имплементации для vulkan и cuda и нет никакой возвожности контролировать, что имплементации одинаковые, кроме как руками сверять код, а это плохо. Либо тогда надо генерировать все функции из одного источника и делать этот шаг дополнительным шагом в сборке. Это надо обдумать.

2024-03-04 12:52 UTC, DimaTrushin commented on lib/shaders/RayleighDerivative1.comp
> +#version 460
Что означает эта версия? Вопрос вот к чему. Когда я генерировал для cuda код, то там было много разных версий api и для того, чтобы они были обратно совместимы или запускались на машине, где этот api не поддерживаетя, требовались дополнительные танцы с бубном. Важно, чтобы код не упал ни на какой машине. То есть должны поддерживаться все версии vulkan или vulkan gate просто не должен стартовать.

2024-03-04 12:52 UTC, DimaTrushin commented on lib/kompute_manager.h
> +namespace NKomputeManager {
Обрати внимание, что у меня все классы посвященные вычислению живут в
```cpp
namespace NSApplication {
namespace NSCompute {
...
}
}
```

2024-03-04 12:52 UTC, DimaTrushin commented on lib/kompute_manager.h
> +class TKomputeManager {
Начинай названия классов с заглавное C, например CKomputeManager. Но может быть лучше назвать CVulkanGate для единообразия с терминологией в проекте. Кроме того, Kompute может сбить с толку особенно со словом Manager, как будто этот объект менеджерит вообще все вычисления.

2024-03-04 12:52 UTC, DimaTrushin commented on lib/kompute_manager.h
> +    using TSequencePtr = std::shared_ptr<kp::Sequence>;
1) КАКОГО ХУЯ ТУТ ДЕЛАЕТ shared_ptr на неконстантный объект с value semantics? Убрать все упоминания shared_ptr из кода любыми средствами. Тебе никогда они НЕ нужны нигде ни при каких условиях. Что мешало сделать unique_ptr?
2) Зачем нужен этот объект? Что ты пытаешься с помощью него достичь?

2024-03-04 12:52 UTC, DimaTrushin commented on lib/kompute_manager.h
> +class TKomputeManager {
Если это высокоуровневая обертка, то мне не нравится глобально, что тут написано. Слишком много какой-то работы. Посмотри на код у меня в проекте:
```cpp
class CCudaGate {
  using CCudaGateImpl = NSCudaGateDetail::CCudaGateImpl;
  using CUptr = std::unique_ptr<CCudaGateImpl>;
public:
  CCudaGate();
  bool isAvailable() const;
private:
  CUptr Gate_;
};
```
Задача класса лишь держать в себе ресурс и все. Impl объект в конструкторе кидает исключение, если его нельзя построить. И эта обертка лишь проверяет можно ли построить gate к ресурсу. Почему у тебя тут есть какие-то странные дополнительные типы и методы?

2024-03-04 12:52 UTC, DimaTrushin commented on lib/kompute_manager.h
> +    bool IsAvaliable() const noexcept {
Почему имплементация не вынесена в cpp файл?

2024-03-04 12:52 UTC, DimaTrushin commented on lib/kompute_manager.h
> +    KomputeManagerHolder Manager;
1) Переменные класса являются глобальными ресурсами для методов класса. Потому нужен механизм отличать их от локальных переменных методов класса. Для этого лучше добавлять либо _ в конце имени, либо m_ в начале, либо что-то подобное. В проекте используется _ в конце имени.
2) Названия луше привести в соответствие с принятым для Cuda.
```cpp
class CVulkanGate {
  using CVulkanGateImpl = NSVulkanGateDetail::CVulkanGateImpl;
  using CUptr = std::unique_ptr<CVulkanGateImpl>;
public:
  CVulkanGate();
  bool isAvailable() const;
  // другие методы релевантные для объекта.
private:
  CUptr Gate_;  
};
```

2024-03-04 12:52 UTC, DimaTrushin commented on lib/kompute_manager.h
> +
Убери лишние вертикальные пробелы между полями класса.

2024-03-04 12:52 UTC, DimaTrushin commented on lib/kompute_manager.h
> +    TSequences Sequences;
Зачем нужна эта переменная? Почему этот объект должен заботиться о какой-то последовательности указателей? Почему это не часть имплементации?

2024-03-04 12:52 UTC, DimaTrushin commented on lib/kompute_manager.h
> +    }
Хорошо бы добавить еще и const версию.

2024-03-04 12:52 UTC, DimaTrushin commented on lib/kompute_manager.h
> +    TSequences GetComputeSequences() {
Что это за хрень, да еще и нет const квалификатора?

2024-03-04 12:52 UTC, DimaTrushin commented on lib/kompute_manager.h
> +    explicit TKomputeManager();
Лишнее слово explicit. Оно имеет смысл лишь для:
1) конструкторов которые могут быть вызваны с 1 аргументом.
2) операторов конвертации типов.
В этом случае это слово ничего тебе не дает.

2024-03-04 12:52 UTC, DimaTrushin commented on lib/kompute_manager.h
Хорошая идея с noexcept везде где можно. Мне еще надо везде это все внедрить.

2024-03-04 12:52 UTC, DimaTrushin commented on lib/kompute_manager.h
> +#pragma once
Обрати внимание, что в проекте пока используются макро гарды. Я планирую переехать на #pragma once. Так что это можно оставить.

2024-03-04 12:52 UTC, DimaTrushin commented on lib/kompute_manager.h
> +#include <kompute/Manager.hpp>
На сколько вообще разумно ссылаться именно на kompute, а не на vulkan? Мне казалось, что это более удобная обертка вокруг вулкана. Использование kompute принципиально отличается от использования vulkan?

2024-03-04 12:52 UTC, DimaTrushin commented on lib/kompute_manager.cpp
> +        //TODO exception handling
Это можно скопировать из кода про Cuda
```cpp
  try {
    Gate_ = std::make_unique<CVulkanGateImpl>();
    qDebug() << "Vulkan is available\n";
  } catch (...) {
    qDebug() << "Vulkan Gate Error\n";
  }
```

2024-03-04 12:52 UTC, DimaTrushin commented on lib/kompute_manager.cpp
> +        }
Что это за хуйня? Почему она не в имплементации менеджера?

2024-03-04 12:52 UTC, DimaTrushin commented on lib/kompute_manager.cpp
> +        //TODO choose best device
Это должно быть НЕ тут. Задача этого объекта -- попытаться инициализировать Gate_ через Vulkan api и хранить доступ к этим ресурсам, а если не получилось, сообщить через isAvailable, что этого сделать нельзя. Все манипуляции с ресурсом выполняются в классе, который отвечает за эти самые ресурсы, а НЕ тут.

2024-03-04 12:52 UTC, DimaTrushin commented on lib/kompute_device.h
> +                   TVectorD* D0Y2, TVectorD* D1Y2);
Этого метода тут быть не должно. Это не задача девайса заниматься конкретной работой. Этот метод должен быть в math модуле, который хранит в себе Gate-ы на все ресурсы и в зависимости от того, какой ресурс сказано использовать выбирает доступ к нужным ресурсам. Я думаю, что тебе надо сейчас перед внедрением в проект создать еще один класс, который будет хранить VulkanGate (то что у тебя сейчас называется TKomputeManager) и уже у этого класса реализовать эту функцию, а тут ты занимаешься только инициализацией устройства и ничем больше.
Задача имплементации:
1) попытаться инициализировать все ресурсы друг за другом и в случае любой проблемы кидать исключение.
2) предоставлять доступ к тем ресурсам, которые необходимы математическому модулю.

2024-03-04 12:52 UTC, DimaTrushin commented on lib/kompute_device.h
> +    using TSequencePtr = std::shared_ptr<kp::Sequence>;
Убрать все shared_ptr
Я понял. Kompute приводит примеры с shared_ptr. Надо
1) Понять нужны ли они реально, и почему именно shared_ptr, почему не unique_ptr и почему не голые конструкторы.
2) Надо в названии отражать, что это shared_ptr. Иначе хер помешь, что он shared.
Но я в любом случае думаю, что не может быть, что нужны shared_ptr, это очень странно. Потому что они же не могут жить на устройстве, когда память качается в gpu, там должны быть свои структуры данных (там вообще все низкоуровневое), потому он внутри все равно должен модифицировать это во что-то другое. Надо с этим разобраться!

UPD: Я думаю, что несмотря на то, что у  Kompute в api висят shared_ptr, мы можем это все обойти. Мы можем мувать в их api свои конейнеры и мувать из их результатов в свои контейнеры. Тогда это должно помочь обойтись без shard_ptr на нашей стороне вообще.

2024-03-04 12:52 UTC, DimaTrushin commented on lib/kompute_manager.h
> +    using KomputeManagerHolder = std::unique_ptr<kp::Manager>;
У меня все больше и больше вопросов. Как я понял, kp::Manager -- это класс из Kompute напрямую. Но тогда вопрос, почему у тебя TKomputeDevice и TKomputeManager хранят указатель на него? Какая роль тогда у менеджера? Как сделано сейчас у меня:
```cpp
namespace NSCudaGateDetail {
class CCudaDevices {
  // Роль класса получить доступ к девайсам доступным через Cuda api
  // Он ничего не инициализирует для работы, лишь служит источником информации об устройствах
  // При любой неудаче в конструкторе кидается исключение.
  // Это вспомогательный класс helper.
};

class CCudaGateImpl : protected CCudaDevices {
  // Этот класс уже инициализирует нужное устройство через Cuda api. Он наследуется от CCudaDevices
  // значит ему доступна вся информация об устройствах через это api. И уже этот персонаж занимается
  // поиском самого быстрого устройства и инициализацией всех ресурсов для начала работы. Этот же
  // персонаж предоставляет необходимый доступ для внешних пользователей к инициализированному
  // устройству. Но ничего больше он не делает. При любой неудаче в конструкторе кидается исключение.
};
}

class CCudaGate {
  // Суть класса в том, чтобы попытаться инициализировать CCudaGateImpl и если получится, то хранить
  // его и получать через него доступ к ресурсам. Никакой другой работы он не выполняет.
  using CCudaGateImpl = NSCudaGateDetail::CCudaGateImpl;
  using CUptr = std::unique_ptr<CCudaGateImpl>;
public:
  CCudaGate();
  bool isAvailable() const;
private:
  CUptr Gate_;
};
```

Потому все Kompute специфичные вещи должны жить в Impl объекте а последний класс -- это лишь перехватчик исключений для конструктора реального объекта, который получает доступ к ресурсам.

2024-03-04 12:52 UTC, DimaTrushin commented on lib/kompute_device.h
> +        std::vector<std::shared_ptr<TPlotComputeFunction>>;
Блять. Какого хуя?

2024-03-04 12:52 UTC, DimaTrushin commented on lib/kompute_device.h
> +    const TSequences Sequences = Manager.GetComputeSequences();
Никогда НЕ создавай константные поля в классе. Для чего это нужно?
Судя по всему это какой-то временный объект, который нужен только вовремя вычисления. НЕ ЗАВОДИ поля класса, которые нужны только внутри одного конкретного вызова одной конкретной функции. Ты забудешь их правильно почистить перед следующим вызовом я тебе гарантирую и вообще это плохая логика.

2024-03-04 12:52 UTC, DimaTrushin commented on lib/compute_function.h
> +using TDataType = float;
Почему тип данных не double, а float?

2024-03-04 12:52 UTC, DimaTrushin commented on lib/compute_functions.h
> +        return NNormalDerivative0::SpirvRawData;
Что тут происходит?
Почему такое ублюдское название после квалификатора доступа?

2024-03-04 12:52 UTC, DimaTrushin commented on lib/compute_functions.h
> +#include "shaders/NormalDerivative0.comp.spv.hpp"
1) Почему эти штуки сгенерированы, а не написаны руками?
2) Почему такие ублюдские названия?

2024-03-04 12:52 UTC, DimaTrushin commented on lib/compute_functions.h
> +template <int64_t derivative>
Добавь guard
```cpp
template<int64_t derivative, class = std::enable_if_t<(derivative < 3)>>
```
чтобы при попытке вызывать TNormal<3> вместо полотна ошибок ты получил сообщение, что такого шаблона нет.

2024-03-04 12:52 UTC, DimaTrushin commented on lib/compute_functions.h
> +template <>
Почему шаблон инстанциируется прямо в хедере? Почему не в cpp файле?

2024-03-04 12:52 UTC, DimaTrushin commented on lib/compute_function.h
> +    TPlotComputeFunction(TTensorPtr&& means, TTensorPtr&& args,
Если что ты понимаешь, что это все rvalue reference, а не universal reference? Это так и задумано?

2024-03-04 12:52 UTC, DimaTrushin commented on lib/compute_function.h
> +        : OpAlgoDispatch(algorithm), OutTensor(out), OutVec(outVec) {
где std::move? У тебя же rvalue reference должно быть как минимум
```cpp
OpAlgoDispatch(std::move(algorithm))
```
и так далее.

2024-03-04 12:52 UTC, DimaTrushin commented on lib/compute_function.h
> +        : OpAlgoDispatch(algorithm), OutTensor(out), OutVec(outVec) {
Почему имплементация в хедере!?

2024-03-04 12:52 UTC, DimaTrushin commented on lib/compute_function.h
> +        assert(dynamic_cast<kp::TensorT<TDataType>*>(means.get()) &&
Почему dynamic_cas??? И вообще какого хрена тут происходит? У тензоров что есть какая-то иерархия и ты по ней гуляешь? Что за чушь тут написана?

2024-03-04 12:52 UTC, DimaTrushin commented on lib/compute_function.h
> +class TPlotComputeFunction : public kp::OpAlgoDispatch {
В названии класса никак не отражено, что он тесно связан с Kompute.

2024-03-04 12:52 UTC, DimaTrushin commented on lib/compute_function.h
> +using TDataType = float;
Убрать все using-ги из namespace-ов и поместить их в релевантные классы в начале в приватной части. Если using-ги используются другим классом, то раскрыть их и выдергивать оттуда.

2024-03-04 12:52 UTC, DimaTrushin commented on lib/compute_function.h
> +    static std::shared_ptr<TPlotComputeFunction> CreateComputeFunction(
1) Нахуя тут создавать shared_ptr, если ты можешь вернуть объект. Если его надо будет воткнуть в Kompute api, то просто мувнишь туда эту функцию и все. Он автоматом откастится к shared_ptr. И не надо будет возиться на нашей стороне с этой хуйней.
2) Плохое длинное название метода. Ты посмотри как ты это будешь звать
```cpp
TPlotComputeFunction::CreateComputeFunction(...);
```
У тебя ComputeFunction встречается в этом выражении дважды. Что мешает функцию просто назвать create?
3) У меня соглашение, что названия ВСЕХ функций начинаются с маленькой буквы.

2024-03-04 12:52 UTC, DimaTrushin commented on lib/compute_function.h
> +        TAlgorithmPtr algorithm, TVectorD* outVec) {
Почему конструктор принимает по rvalue reference, а здесь принимаешь by value? Не консистентно.

2024-03-04 12:52 UTC, DimaTrushin commented on lib/compute_function.h
> +        auto* fromEnd = fromBegin + OutTensor->size();
А что у тензора нет итераторов begin и end?

2024-03-04 12:52 UTC, DimaTrushin commented on lib/compute_functions.h
> +    static TSpirvProgrammConstRef Get() {
1) Что это за ебнутое название типа TSpirvProgrammConstRef? Сам придумал или кто подсказал?
2) Функция Get с маленькой буквы get

2024-03-04 12:52 UTC, DimaTrushin commented on lib/kompute_device.cpp
> +}
Зачем?

2024-03-04 12:52 UTC, DimaTrushin commented on lib/kompute_device.cpp
> +}
Это для чего?

2024-03-04 12:52 UTC, DimaTrushin commented on lib/kompute_device.cpp
> +}
Что это за хрень!? Из названия я вижу, что она должна заполнять выходной тензор. Но функция при этом не возвращает ничего (return void). Она не принимает выходной аргумент. А значит ты манипулируешь состоянием. Это плохо. Что за поебень DefaultSequence? Судя по всему ты через эту хуйню пытаешься возвращать значение. Что мешает простов вернуть значение by value? Что вообще тут происходит?

2024-03-04 12:52 UTC, DimaTrushin commented on lib/kompute_device.cpp
> +    // TODO rewrite
Что означает этот комментарий? Тут что-то не верно написано или что?

2024-03-04 12:52 UTC, DimaTrushin commented on lib/kompute_device.cpp
> +                  [](auto seq) { seq->evalAwait(); });
Я правильно понимаю, что тебе было лень писать 6 блоков кода для 6 видов вычислений и тты так это оптимизировал в последовательность?

2024-03-04 12:52 UTC, DimaTrushin commented on lib/kompute_device.cpp
> +    }
Нарушение уровня абстракции, у тебя до и после идут вызовы функций с говорящи ми названиями, а тут идет низкоуровневый цикл. Рефактор.

2024-03-04 12:52 UTC, DimaTrushin commented on lib/kompute_device.cpp
> +                  [](auto seq) { seq->evalAsync(); });
Названия переменных seq ничего не говорят. Что это за хрень? Это task или что?

2024-03-04 12:52 UTC, DimaTrushin commented on lib/kompute_device.cpp
> +    using namespace NComputeFunctions;
Не надо было помещать функции в отдельный namespace. У меня все живет в NSCompute.

2024-03-04 13:13 UTC, eparoshin commented on lib/shaders/meson.build
да, h файлы можно, могу поменять. кодогенерация нужна, там такая схема работы с шейдерами: пишется шейдер на любом подходящем языке->потом копмилируется в промежуточное представление spirv-> потом уже в виде промежуточного представления отправляется на видеокарту. если избавиться от кодогенерации, компиляция в spirv будет каждый раз происходить перед вызовом любой функции на видеокарте. оверхед я если честно не замерял, но мне кажется, от него в любом случае надо избавитьчя, тем более что тогда еще добавится рантайм зависимость от компилятора шейдеров.

2024-03-04 13:15 UTC, eparoshin commented on lib/kompute_manager.h
> +    TSequences GetComputeSequences() {
Sequence это абстракция над очередями вычисления на видеокарте, метод неконстантный, потому что в Kompute отправка вычислений на Sequence, это неконстантный метод

2024-03-04 13:18 UTC, eparoshin commented on lib/kompute_device.h
> +    using TSequencePtr = std::shared_ptr<kp::Sequence>;
да, там у них к сожалению везде передается shared_ptr, я еще посмотрю как можно максимально от этого избавиться

2024-03-04 13:20 UTC, eparoshin commented on lib/kompute_device.h
> +        std::vector<std::shared_ptr<TPlotComputeFunction>>;
такое api у Kompute( знаю, что выглядит очень плохо, я подумаю еще как это можно обойти

2024-03-04 13:23 UTC, eparoshin commented on lib/compute_function.h
> +using TDataType = float;
double это какое-то нестандартное расширение vulkan, например у меня на встройке ноутбука double не поддерживается, я еще поэксперементирую, насколько float снижают точность, если будет плохо, видимо придется переходить на double. я думал над тем чтобы сделать это настраиваемым при компиляции, но шейдеры придется переписывать целиком, а это сильно усложнит сборку, т.к. придется делать разную кодогенерацию в зависимости от флага, если float будет не сильно хуже, хотелось бы такого избежать.

2024-03-04 13:25 UTC, eparoshin commented on lib/compute_functions.h
> +        return NNormalDerivative0::SpirvRawData;
тут возращается скомпилированный шейдер в бинарном виде, полученный с помощью кодогенерации из хедера. название наверное действительно так себе, поменяю

2024-03-04 13:25 UTC, eparoshin commented on lib/compute_functions.h
> +#include "shaders/NormalDerivative0.comp.spv.hpp"
они компилируются из шейдеров (где-то выше про это писал)

2024-03-04 13:33 UTC, eparoshin commented on lib/compute_function.h
> +        auto* fromEnd = fromBegin + OutTensor->size();
нету(

2024-03-04 13:35 UTC, eparoshin commented on lib/kompute_device.cpp
> +}
принимаю вектор double, а мне нужен вектор float

2024-03-04 13:36 UTC, eparoshin commented on lib/kompute_device.cpp
> +}
Sequence это очередь вычислений на видеокарте, очереди в основном могут вычислять паралельно, идея в том чтобы класть каждое вычисление в следущую очередь

2024-03-04 13:38 UTC, eparoshin commented on lib/kompute_device.cpp
> +    // TODO rewrite
тут скорее надо //TODO refactor. мне не нравится ходить по индексам, кажется можно более аккуратно сделать, но я пока так оставил

2024-03-04 13:42 UTC, eparoshin commented on lib/kompute_device.cpp
> +                  [](auto seq) { seq->evalAwait(); });
нет, в sequence после того как вычсления положили, надо сказать что можно асинхронно начинать считать, и потом дождаться окончания всех вычислений. судя по всему делать evalAsync без evalAwait - это уб, поэтому так мне кажется правильнее всего. если делать для каждого вычисления отдельно, получится синхронно, это будет медленнее

2024-03-04 13:43 UTC, eparoshin commented on lib/kompute_device.cpp
> +                  [](auto seq) { seq->evalAsync(); });
seq - sequence (абстракция над очередью), вызывается таск, который уведомляет видеокарту, что можно начинать считать все что лежит в очереди

2024-03-04 13:47 UTC, eparoshin commented on lib/compute_function.h
> +        assert(dynamic_cast<kp::TensorT<TDataType>*>(means.get()) &&
у тензор это класс где тип хранится в enum, от него наследуется шаблонный TensorT, который по сути этот enum заполняет в зависимости от шаблона. я знаю что dynamic_cast это плохо, но мне кажется в ассерте, более или менее. этот ассерт очень нужен, потому что когда тензор неправильного типа доезжает до видеокарты, это уже нереально дебажить, там очень нестабильно ошибки вылезают. мне казалось, там почему-то не получается сюда явно передать TensorT<TDataType>, но я еще перероверю

2024-03-04 13:50 UTC, eparoshin commented on lib/kompute_device.cpp
> +}
тут вызывается таска, которая говорит видеокарте перенести данные из памяти видеокарты, в оперативную, это нужно сделать чтобы потом из тензора можно было вернуть результат.

2024-03-04 13:52 UTC, eparoshin commented
@DimaTrushin, вроде на все спорные моменты ответил, везде где не ответил, исправлю. я еще вот задумался, раз уж я завендорил Kompute, может его немного пропатчить, чтобы api стало чуть адекватнее, как думаешь, насколько целесообразно?

2024-03-04 13:54 UTC, eparoshin commented on lib/shaders/RayleighDerivative1.comp
> +#version 460
в этой версии добавлялись какие-то расширения для работы с double, но я потом от него отказался, а версию не поправил. как решу окончательно с double, поменяю на минимально возможную

2024-03-04 13:55 UTC, eparoshin commented on lib/kompute_manager.h
> +    using TSequencePtr = std::shared_ptr<kp::Sequence>;
Кажется там нужно его где-то несколько раз как shared_ptr в Kompute передавать. я еще перепроверю, если будет возможно исправлю

2024-03-04 13:59 UTC, eparoshin commented on lib/kompute_manager.cpp
> +        //TODO choose best device
наверное не оч правильный комментарий, тут будет вызываться конструктор из kompute_device, и заполнение sequences тамже, выбирать лучшее устройство прям тут в конструкторе я не собирался

2024-03-04 14:10 UTC, eparoshin commented on lib/kompute_device.h
> +    const TSequences Sequences = Manager.GetComputeSequences();
я планировал один раз создать manager, инициализировать для него все очереди, потом переиспользовать объект, закидывая туда таски для вычислений. заново инициализировать перед каждым вызовом ComputeAsync мне кажется довольно избыточно(тем более что по моим наблюдениям, инициализация vulkan устройства происходит успешно наверное 8 раз из 10, по крайней мере у меня на linux + amd)

2024-03-04 14:13 UTC, eparoshin commented on lib/kompute_manager.cpp
> +        //TODO exception handling
я еще немного поэксперементирую с разными вендорами и ос, потому что возможно туда стоит добавить ретраи, т.к. инициализация может упасть, без видимой на то причны

2024-03-04 14:15 UTC, eparoshin commented on lib/kompute_manager.cpp
> +        }
пока не перенес, планируется что она будет в kompute_device, еще тут пока всегда вектор из одной очереди, т.к. получать эти очереди нужно через сишное апи вулкана, я туда пока еще не залезал

2024-04-08 03:24 UTC, eparoshin commented on test/test_fill_plots.cpp
> +    device.FillPlots(samples, x, &D0Y0, &D1Y0, &D0Y1, &D1Y1, &D0Y2, &D1Y2);
0.23 секунды на встройке intel ~2020 года

2024-04-23 11:06 UTC, eparoshin commented
Основная идея была, т.к. полностью от shared_ptr избавиться не получится, максимально их спрятать. в итоге я засунул все  shared_ptr в класс CFunctionBuilder, объект которого можно получить только обратившись к VulkanGate. после чего все что я могу сделать, это получить контейнер в которой потом будет лежать return value функции. Несмотря на то что это усложняет код, мне кажется так более правильно, т.к. это позволяет спрятать от клиента (функции FillPlots) все shared_ptr, и предоставить ей интерфейс, который выглядит довольно логично: начать серию вычислений -> добавить функции в серию -> выполнить серию -> получить результат

2024-04-23 14:38 UTC, DimaTrushin requested changes
Я накидал каких-то замечаний. Мне в целом нравится больше как теперь разбиты компоненты. Но все равно часть вещей размазана и мутная.
1) Надо kp:manager, который у тебя CDevice, надо запихнуть внутрь CVulkanGate, потому что он отвечает за возможности работы с устройством, за выбор устройства, за копирование на него и с него и потому все эти опции должны предоставляться гейтом.
2) Так же у тебя Builder плохо назван и вообще не Builder. По сути его надо смерджить с CVulkanCompute. Это один и тот же объект, чьи функции размазаны по двум. Ну и у тебя какая-то каша из функций и фьючерсов. Мне надо будет эту кашу разгрести. Но видимо уже не сегодня.

Я надеюсь, что после этого все ссылки у объектов друг на друга просто пропадут. И можно будет писать не хрупкий код.

Так же у тебя какое-то огроменное количество друзей у всего подряд. Это сильно ломает инкапсюляцию.

И еще не уверен, что Gate должен давать доступ к sequences. Это все детали имплементации. Я бы сделал нормальный фасад вокруг kompute api. По сути тебе надо уметь копировать данные на девайс, с девайса и применять алгоритм к таким-то данным. Вот я бы что-то вроде такого фасада хотел видеть.
Правда может быть тогда утекут shared_ptr в api. Но их видимо можно допустить в api для Gate, а вот уже Compute будет заниматься преобразованием данных. Тогда можно будет избежать ненужных CPlotComputeFunction и CFutureResult, которые по сути нужны чтобы спрятать shared_ptr на ответ. Видимо можно позволить утечь shared_ptr внутрь методов Compute. И то тебе придется хранить только shared_ptr на ответы, чтобы потом из них считать данные.

2024-04-23 14:38 UTC, DimaTrushin commented on lib/shaders/meson.build
То есть это разовая акция. Если ты написал код шейдеров, то надо сделать эту генерацию и все. И если больше шейдеры не меняешь, то и не надо ничего конвертировать. Думаю это можно будет потом запихнуть в qmake в отдельный компилятор и тягать его при изменении кода шейдеров.

2024-04-23 14:38 UTC, DimaTrushin commented on lib/vulkan_compute_module.cpp
> +using CVectorD = std::vector<double>;
Используй тут
```cpp
using CVectorD = CVulkanCompute::CVectorD;
```
Иначе у тебя зависимости поедут, если ты сменишь в одном месте.

2024-04-23 14:38 UTC, DimaTrushin commented on test/test_fill_plots.cpp
> +using CVectorD = std::vector<double>;
Не делай глобальных using-гов. Помести его внутрь main.

2024-04-23 14:38 UTC, DimaTrushin commented on test/test_fill_plots.cpp
> +void printvec(const std::vector<double>& vec) {
Все функции, что определяются в cpp файлах должны быть выделены в anonymous namespace.

2024-04-23 14:38 UTC, DimaTrushin commented on test/test_fill_plots1.cpp
> +void printvec(const std::vector<double>& vec) {
Ты эту функцию используешь в нескольких cpp файлах, выдели отдельно.

2024-04-23 14:38 UTC, DimaTrushin commented on test/test_fill_plots.cpp
> +    NSApplication::NSCompute::CVulkanCompute compute(gate);
Мне внешне не нравится идея, что надо compute инициализировать от гейта. Технически гейт может закрыться, а compute еще жить. Я посмотрю на имплементацию и подумаю, что бы я сделал.

2024-04-23 14:38 UTC, DimaTrushin commented on lib/vulkan_gate.h
> +    CDevicesInfoContainer getDevices() const;
Не возвращай контейнеры по копии, возвращай по константной ссылке. Старайся всегда избегать копирования любых контейнеров.

2024-04-23 14:38 UTC, DimaTrushin commented on lib/vulkan_gate.cpp
> +CVulkanGate::~CVulkanGate() = default;
Порядок методов в cpp файле должен совпадать с порядком методов в h файле. Как потом искать, где какой метод определен?

2024-04-23 14:38 UTC, DimaTrushin commented on lib/compute_function.h
> +using CAlgorithmShared = std::shared_ptr<kp::Algorithm>;
Убери все псевдонимы из пространства имен. Невозможно уследить за тем, что где определяется. Это плохие глобальные зависимости. Определяй все необходимые псевдонимы в начале каждого класса. Если класс должен подтягивать эти псевдонимы из другого класса, то подтягивай их оттуда для согласования.

Вот пример. У тебя тут определяется CTensorPtr, а потом внутри следующего класса CTensorShared. Во-первых, это выглядит как ошибка как будто ты определил два разных псевдонима для одного типа. А во-вторых, имена такие, что от этого нет никакого толку.

2024-04-23 14:38 UTC, DimaTrushin commented on lib/compute_function.h
> +using CSpirvProgrammConstRef = const CSpirvProgramm&;
Создавать псевдоним для константной ссылки не стоит.

2024-04-23 14:38 UTC, DimaTrushin commented on lib/compute_function.h
> +    friend class CFutureResult;
Наличие друзей означает, что они должна шарить общий инвариант. А это обычно бывает только при имплементации какого-то паттерна. Что-то мне подсказывает, что тут вряд ли какой-то паттерн имплементирован. Точнее, если у Builder-а я верю, что это действительно важно быть friend, чтобы получить доступ к приватному конструктору. То что тут делает CFutureResult, я не понимаю.

2024-04-23 14:38 UTC, DimaTrushin commented on lib/compute_function.h
> +    friend class CFunctionBuilder;
В чем вообще необходимость Builder-а? Неужели конструктора или просто статического метода не хватает для нужных целей?

2024-04-23 14:38 UTC, DimaTrushin commented on lib/compute_function.h
> +class CFunctionBuilder {
Судя по функционалу это НЕ builder. Задача билдера заключается только в том, чтобы можно было построить объект в несколько шагов и пока мы его строим, внутри билдера объект хранится в промежуточном и пока еще не корректном состоянии. И суть билдера уметь поддерживать эти промежуточные некорректные состояния и потом возвращать только корректную версию объекта. У тебя же этот класс занимается совсем другой деятельностью. Он хранит все Functions и потом еще запускает их все. У тебя намешана логика страшным образом.

2024-04-23 14:38 UTC, DimaTrushin commented on lib/compute_function.h
> +        return createFunction(TShaderGetter::Get());
Охренеть название. У тебя метод говорит, что он создает функцию, а на самом деле возвращает Future. Никогда так НЕ делай. НЕ обманый программистов своим кодом.

2024-04-23 14:38 UTC, DimaTrushin commented on lib/compute_function.h
> +    const CVulkanGate& Gate_;
НИКОГДА НЕ храни ссылки на другие объекты. Это разрушает value semantics и делает твои объекты хрупкими. Любой переезд Gate_ или уничтожение приводит к некорректному состоянию этой пары. Проект не просто так использует observer pattern для общения компонент, это позволяет гарантировать корректность. Ты тут сейчас ломаешь просто всю парадигму правильного общения компонент. Я подумаю над правильным дизайном.

2024-04-23 14:38 UTC, DimaTrushin commented on lib/compute_function.h
> +    friend class CVulkanGate;
Еще один friend. Такое количество друзей означает систематическое нарушение инкапсюляции всеми классами. А это уже ошибка дизайна. Такого большого количества транзитивных друзей быть НЕ должно. Теперь для понятия того, как взаимодействуют классы, мне НЕ достаточно знать их публичные интерфейсы, мне надо знать их все приватные методы, приватные данные и их имплементации. Это ничем НЕ лучше, чем все написать с помощью глобальных переменных.

2024-04-23 14:38 UTC, DimaTrushin commented on lib/compute_function.cpp
> +                         kp::Workgroup({args->size(), 1, 1}));
Ну охуеть, у тебя конструктор делает содержательную работу. Суть конструктора в том, чтобы построить объект в корректном состоянии и все. Но беда в том, что у тебя этот класс не имеет назначения, он является какой-то поебенью, потому и конструктор ведет себя так же.

2024-04-23 14:38 UTC, DimaTrushin commented on lib/compute_function.cpp
> +    algorithm->rebuild<>({means, args, OutTensor_}, shader,
Странно, что out ты мувнул в OutTensor_, а тут внезапно means и args не муваются.

2024-04-23 14:38 UTC, DimaTrushin commented on lib/compute_function.h
> +    CFunctionBuilder(const CVulkanGate& gate, CDevice& device,
Очень плохая сигнатура конструктора. Дело в том, что суть VulkanGate в том, чтобы через него получать доступ ко всем ресурсам вычислительным. Тогда вознимает вопрос, а схуя ли нам еще нужно какой-то Device указывать? Что, gate сам не может разобраться, как ему работать?

2024-04-23 14:38 UTC, DimaTrushin commented on lib/compute_function.cpp
> +    Functions_.emplace_back(new CPlotComputeFunction(
Если используешь умные указатели вроде unique_ptr или shared_ptr, то НЕ используй new в коде, а используй make_unique или make_shared соответственно. Так ты сообщаешь читателю кода, что за указатели тут используются. Иначе мне надо лезть в определение Functions_ и проверять, а не сырые ли блять указатели тут воткнули и у нас память потечет как хуй знает что.

2024-04-23 14:38 UTC, DimaTrushin commented on lib/vulkan_gate.h
> +class Instance;
Вот этот класс тут нигде не используется

2024-04-23 14:38 UTC, DimaTrushin commented on lib/vulkan_gate.h
> +class Manager;
Этот класс тут нигде не используется

2024-04-23 14:38 UTC, DimaTrushin commented on lib/sliding_container.h
> +        Idx_ = (Idx_ + 1) % CBase::size();
Это что за хрень? Как у тебя код после return выполняться будет?

2024-04-23 14:38 UTC, DimaTrushin commented on lib/sliding_container.h
> +        return CBase::at(Idx_);
Ты понимаешь, что at кидает исключения?

2024-04-23 14:38 UTC, DimaTrushin commented on lib/sliding_container.h
> +    mutable size_t Idx_{0};
Плохая тема использовать mutable. Потому что по сути у тебя этот объект логически меняется. А значит у него меняется состояние. Вообще ты пытаешься смешать бульдога с носорогом. То что ты тут пишешь, это версия итератора. А ты смешал его с контейнером. Да еще и закрыл конструкторы контейнера. Не вижу смысла в целом в этом классе. Дичь какая-то.

2024-04-23 14:38 UTC, DimaTrushin commented on lib/vulkan_compute_module.cpp
> +    std::vector<CDataType> args(x.begin(), x.end());
Ты потом внутри createFunctionBuilder будешь снимать копии с этих векторов и складывать их в shared_ptr. Потому нет смысла тут это делать. Я бы в createFunctionBuilder передавал бы исходные векторы и уже там делал построение копий внутри shared_ptr.

2024-04-23 14:38 UTC, DimaTrushin commented on lib/vulkan_compute_module.cpp
> +    auto builder = Gate_.createFunctionBuilder(means, args);
Мне бы очень хотелось бы суметь means и args прицепить к алгоритму. Но без манипуляции с shared_ptr пока не вижу легкого способа это сделать.

2024-04-23 14:38 UTC, DimaTrushin commented on lib/compute_function.h
> +    CDevice& Device_;
Вот этот товарищ отвечает за выбор девайса, его настройки, используемые ресурсы. А так же он умеет пересылать данные на девайс и обратно, умеет добавлять операции, которые надо исполнить и исполнять их. Это выглядит как часть CVulkanGate. И по логике вот этот класс, который ты назвал FunctionBuilder это как раз аналог Math модулф у меня. И он уже должен пользоваться gate-ом для подобных махинаций. Суть гейта в том, чтобы либо протолкнуть api либо сделать вокруг него фасад. И все активации должны делаться внутри за этим гейтом. В целом выглядит так что надо слить воедино Builder и VuilanCompute. Ибо у тебя между ними размазаны общие какие-то знания и функции.

2024-04-23 14:38 UTC, DimaTrushin commented on test/test_fill_plots.cpp
> +    NSApplication::NSCompute::CVulkanCompute compute(gate);
Я подумал над использованием. Твой CVulkanCompute, это аналог моего CMath. Потому CVulkanCompute должен внутри себя создавать  CVulkanGate и првоерять, если он доступен, то выполнять вычисления на нем, если нет, то например ничего не делать. А потом уже будет с такой логикой его легче пересадить внутрь CMath в рамках проекта.

Теперь если посмотреть на работу CVulkanCompute, он у тебя делегирует кучу работы либо к Builder либо к Device (который на самом деле kp::manager). Так вот. Я бы Device загнал бы внутрь CVulkanGate, ибо это часть которая должна выбрать самый быстрый девайс если он есть. Он же отвечает за методы пересылки данных с хоста на девайс и обратно и за старт и финиш вычислений. Потому я бы эту штуку завернул бы внутрь Gate-а. И тягал бы из гейта нужные методы с нужными интерфейсами.

2024-04-23 14:38 UTC, DimaTrushin commented on lib/compute_function.h
> +        const CPlotComputeFunction& Self_;
А что мешает тут хранить shared_ptr на исходную функцию? Если она умрет к моменту, когда кто-то запросит данные из Future?

2024-04-23 14:38 UTC, DimaTrushin commented on lib/compute_function.cpp
> +                      sequences.getAndSlide()->record(std::move(func));
Ну вот и раскрылся ларчик. Ты смешал бульдога с носорогом и получил чебурашку. Тебе не нужен контейнер с дополнительным функционалом. Тебе нужен новый вид итератора. И не понятно, что мешало использовать просто итератор.

2024-04-23 14:38 UTC, DimaTrushin commented on lib/compute_function.cpp
> +    std::for_each(Functions_.begin(), Functions_.end(),
Я не очень понимаю сути происходящего тут. Что делает этот цикл? Ты проходишь по всем sequence, которые есть в Gate и в каждую из них кладешь функцию? Это типо попытка распараллелить вызов функций в разных очередях на девайсе? Если так, то это не факт, что работает (там даже простыня на сайте Kompute по этому поводу написана на примере gforce 1650).

2024-04-23 14:38 UTC, DimaTrushin commented on lib/vulkan_compute_module.cpp
> +    std::vector<CDataType> means(samples.begin(), samples.end());
Ты где-то создаешь вектор строчкой
```cpp
std::vector<...> vec1(vec2);
```
а где-то
```cpp
std::vector<...> vec1(vec2.begin(), vec2.end());
```
Ясен хрен, что первый способ лаконичнее и более читаемый.

2024-04-23 15:01 UTC, eparoshin commented on lib/compute_function.cpp
> +    std::for_each(Functions_.begin(), Functions_.end(),
Ага, это распарралеливание функций, я специально для этого при создании беру только очереди из разных queue family, так что при наличии таких очередей распарралеливание будет, а если нет, то будет тоже самое, что сабмитить явно в одну очередь

2024-04-29 20:04 UTC, eparoshin commented
Сделал в итоге так: CplotComputeFunction хранит means, и алгоритм шейдера, и ничего не знает про конкретный инстанс вулкана, функцию можно вызвать с аргументом args, с помощью CVulkanGate, и сразу получить результат. CVulkanGate инициализирует все вспомогательные структуры, передаст их в CPlotComputeFunction, выполнит, и вернет результат, аргументы для вызова функций можно получить только с помощью CVulkanGate. Поразбирался еще с очередями, в итоге думаю, что было лишнее, в нашем конкретном случае, когда нужно просто обработать заранее известное конечное количество данных, за короткое время, разницы особо не будет. Разные семейства очередей больше подойдут, если на видеокатру будет постоянная высокая нагрузка, и считать нужно парралельно. Код не окончательный, еще буду исправлять, хочу только зафиксировать все классы, чтобы описать их в отчете

2024-05-05 12:08 UTC, DimaTrushin requested changes
В целом мне очень нравится, что сейчас получается. Теперь все достаточно компактно сосредоточено. Единственное я бы предложил вынести из функции логику связанную с алгоритмами (и потому все kompute зависимые действия) в callFunction метод из Gate-а. Я сделал поментки по коду как я это вижу (по модулю того, что я не до конца понимаю как правлиьно пользоваться kompute вызовами).

После этого остались лишь мелочи вроде имен методов и классов и разбивки на файлы.

И еще хочется вернуться к вопросу возможности перехода на double в компилируемых шейдорах.

2024-05-05 12:08 UTC, DimaTrushin commented on lib/compute_function.h
> +    CSharedTensor Out_;
Я бы убрал эти данные из функции и создавал бы функцию только с данными, которые имеют смысл между вызовами. То есть аргументы и выходной тензор я бы убрал. Пусть функция будет абстракцией над операцией с забиндинными данными.

2024-05-05 12:08 UTC, DimaTrushin commented on lib/compute_function.h
> +    CSharedOp getSyncOutputOp();
Я бы убрал эти два метода, этот функционал надо перенести в GateImple в метод callFunction.

2024-05-05 12:08 UTC, DimaTrushin commented on lib/compute_function.h
> +    CVector getResultVec();
Этот метод я бы просто убрал.

2024-05-05 12:08 UTC, DimaTrushin commented on lib/compute_function.h
> +    friend class NSVulkanGateDetails::CVulkanGateImpl;
Убери френда. Я не вижу в нем смысла.

2024-05-05 12:08 UTC, DimaTrushin commented on lib/compute_function.h
> +        return CPlotComputeFunction(TShader::Get, std::move(means));
Назови статический метод Code вместо Get. Будет читаемее.

2024-05-05 12:08 UTC, DimaTrushin commented on lib/compute_function.cpp
> +
Я бы создавал Args и Out в callFunction и там же вызывал rebuild. Но для этого тебе надо из функции вытащить ее забинденные параметры и ее код. Потому я бы сделал два метода means() и code() у функции и звал бы явно как-то так
```cpp
device_->algorithm()->rebuild<>({func.means(), args, out}, func.code(), shape(args));
```
И потом уже выкачивал бы данные из out. И функция освобождена от этих действий. Ей не надо хранить агрументы и выходной контейнер между запусками, что идейно не верно.

2024-05-05 12:08 UTC, DimaTrushin commented on lib/compute_function.cpp
> +    return std::make_shared<kp::OpTensorSyncLocal>(std::vector<std::shared_ptr<kp::Tensor>>{Out_});
Вот это я не понимаю почему так сложно написано. Ты создаешь shared_ptr и вектора состоящего из shared_ptr-ов на тензоры. Ты же просто хочешь перенести данные с девайса в хост или я не прав? Что-то странное тут.

2024-05-05 12:08 UTC, DimaTrushin commented on lib/vulkan_compute_module.cpp
> +    auto args = Gate_.createAndSyncTensor(convert(x));
1) Я бы переименовал эти меоды в copyToDevice, потому что ты именно это делаешь.
2) У тебя тут происходит одно лишнее неявное копирование. Во первых, ты делаешь convert, которые строит временный объект, а дальше ты принимаешь его по константной ссылке, а значит, ты не можешь своровать внутренности и когда ты потом грузишь в shared_ptr на тензор, у тебя происходит еще одно копирование временного объекта. Я думаю, что createAndSyncTensor (который стоит переименовать в copyToDevice) должна принимать вектор по rvalue reference и потом всюду мувать данные.

2024-05-05 12:08 UTC, DimaTrushin commented on lib/vulkan_compute_module.cpp
> +    *D0Y0 = convert(Gate_.callFunction(normal0F, args));
Тут одно замечание. Я бы хотел иметь все выходные массивы уже преаллоцированными, потому я бы выгружал данные каждый из этих массивов, а не мувал результат. Это особенность дизайна ядра программы. В целом это не очень принципиально. Пусть будут обе версии.

2024-05-05 12:08 UTC, DimaTrushin commented on lib/vulkan_gate.cpp
> +        auto functionCallOp = func.getFunctionCallOp(Device_->algorithm(), args, Device_->tensorT(outData));
Вот тут проблема. Ты создаешь вектор, а потом копируешь его в тензор на девайсе вместо мува. Я бы вообще сделал не так. Я думаю, что тут я бы сделал так.
```cpp
CSharedTensor out = std::make_shared<...>(args->size());
device_->algorithm()->rebuild<>({func.means(), args, out}, func.code(), shape(args));
// тут надо построить аналоги твоих functionCallOp и syncOutputOp (который надо переименовать в moveFromDevice).
Device_->sequence()->record(functionCallOp)->eval(syncOutputOp);
// ну и теперь надо запросить данные из out, причем я бы их мувал отсюда как-то так
return std::move(*out);
```
Еще сделай доп функцию shape, чтобы не возиться с указанием workgroup руками. Если так сделать, то вся соержаельная работа будет находиться только в этом методе (кроме закачки общих данных, которые будут в методе fillPlots.

2024-05-05 12:08 UTC, DimaTrushin commented on lib/vulkan_gate.h
> +    CSharedTensor createAndSyncTensor(const CVector& vec);
1) переименуй в copyToDevice
2) Принимай аргумент как CVector&&. Ты все равно подставляешь сюда всегда трансформированные данные из даблов во флоаты, потому у тебя тут всегда временный объект, который хотелось бы украсть в самый последний момент, когда ты складываешь данные в shared_ptr.

2024-05-05 12:08 UTC, DimaTrushin commented on lib/vulkan_gate.h
> +    CVector callFunction(CPlotComputeFunction& func, CSharedTensor args);
после моих рекомендаций тут можно func передавать по константной ссылке.

2024-05-05 12:08 UTC, DimaTrushin commented on lib/vulkan_gate.cpp
> +    return Gate_->createAndSyncTensor(vec);
1) добавь тут assert-ы и везде, где ты пытаешься получать доступ по указателю.
2) изменить на CVector&& и сделай std::move(vec); при передаче данных дальше.

2024-06-04 19:58 UTC, merged